#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"

TMP_FILE=$(mktemp)
GH_API=https://api.github.com/repos/foswiki/distro/releases/latest
curl -s $GH_API > $TMP_FILE
LATEST_TAG=$(cat $TMP_FILE | grep -oP '"tag_name": "\K(.*)(?=")')
LATEST_FILE="$(cat $TMP_FILE | grep -oP -m 1 '"name": "\K(.*)(?=")' | tr ' ' '-').tgz"
rm -f $TMP_FILE
URL="https://github.com/foswiki/distro/releases/download/$LATEST_TAG/$LATEST_FILE"

dl $URL $SRC
