#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"

VERSION="2.1.6"
URL="http://sourceforge.net/projects/foswiki/files/foswiki"

dl $URL/$VERSION/Foswiki-$VERSION.tgz $SRC

