#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/foswiki

# unpack foswiki, overlay foswiki configuration
tar -zxf $SRC/Foswiki-*.tgz -C $(dirname $WEBROOT)
rsync -a /var/www/Foswiki-*/ $WEBROOT
rm -r /var/www/Foswiki-*

echo -e 'y\n' | cpan 
cpan install Canary::Stability Crypt::PasswdMD5 File::Copy::Recursive JSON

CONFIG="perl -CA $WEBROOT/tools/configure -save" 
$CONFIG -noprompt # auto default config (writes config as root)
$CONFIG \
    -set {EnableEmail}='1' \
    -set {Email}{MailMethod}='MailProgram' \
    -set {MailProgram}='/usr/sbin/sendmail -t -oi -oeq'

chown -R www-data:www-data $WEBROOT

# apache configuration
a2dissite 000-default
a2enmod cgid
a2enmod rewrite
a2ensite foswiki

# cleanup
rm -rf $SRC/Foswiki*
rm -rf $SRC/foswiki*
